// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc

import (
	uuid "github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type ApiKey struct {
	ID         uuid.UUID          `db:"id" json:"id"`
	UserID     pgtype.UUID        `db:"user_id" json:"user_id"`
	Name       string             `db:"name" json:"name"`
	KeyPrefix  string             `db:"key_prefix" json:"key_prefix"`
	KeyHash    string             `db:"key_hash" json:"key_hash"`
	IsActive   bool               `db:"is_active" json:"is_active"`
	CreatedAt  pgtype.Timestamptz `db:"created_at" json:"created_at"`
	LastUsedAt pgtype.Timestamptz `db:"last_used_at" json:"last_used_at"`
}

type RateLimitPolicy struct {
	ID                    uuid.UUID          `db:"id" json:"id"`
	ScopeType             string             `db:"scope_type" json:"scope_type"`
	ScopeIdentifier       pgtype.UUID        `db:"scope_identifier" json:"scope_identifier"`
	RoutePattern          *string            `db:"route_pattern" json:"route_pattern"`
	Capacity              int32              `db:"capacity" json:"capacity"`
	RefillTokens          int32              `db:"refill_tokens" json:"refill_tokens"`
	RefillIntervalSeconds int32              `db:"refill_interval_seconds" json:"refill_interval_seconds"`
	IsActive              bool               `db:"is_active" json:"is_active"`
	CreatedAt             pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type RequestAuditLog struct {
	ID              int64              `db:"id" json:"id"`
	ApiKeyID        pgtype.UUID        `db:"api_key_id" json:"api_key_id"`
	RouteID         string             `db:"route_id" json:"route_id"`
	PolicyID        pgtype.UUID        `db:"policy_id" json:"policy_id"`
	Outcome         string             `db:"outcome" json:"outcome"`
	RequestCost     int32              `db:"request_cost" json:"request_cost"`
	TokensRemaining int32              `db:"tokens_remaining" json:"tokens_remaining"`
	BlockedAt       pgtype.Timestamptz `db:"blocked_at" json:"blocked_at"`
}

type User struct {
	ID        uuid.UUID          `db:"id" json:"id"`
	Name      string             `db:"name" json:"name"`
	Email     string             `db:"email" json:"email"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
}
