// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: rate_limit_policies.sql

package sqlc

import (
	"context"

	uuid "github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createRateLimitPolicy = `-- name: CreateRateLimitPolicy :one
INSERT INTO rate_limit_policies (
    scope_type,
    scope_identifier,
    route_pattern,
    capacity,
    refill_tokens,
    refill_interval_seconds
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
)
RETURNING id, scope_type, scope_identifier, route_pattern, capacity, refill_tokens, refill_interval_seconds, is_active, created_at, updated_at
`

type CreateRateLimitPolicyParams struct {
	ScopeType             string      `db:"scope_type" json:"scope_type"`
	ScopeIdentifier       pgtype.UUID `db:"scope_identifier" json:"scope_identifier"`
	RoutePattern          *string     `db:"route_pattern" json:"route_pattern"`
	Capacity              int32       `db:"capacity" json:"capacity"`
	RefillTokens          int32       `db:"refill_tokens" json:"refill_tokens"`
	RefillIntervalSeconds int32       `db:"refill_interval_seconds" json:"refill_interval_seconds"`
}

func (q *Queries) CreateRateLimitPolicy(ctx context.Context, arg CreateRateLimitPolicyParams) (RateLimitPolicy, error) {
	row := q.db.QueryRow(ctx, createRateLimitPolicy,
		arg.ScopeType,
		arg.ScopeIdentifier,
		arg.RoutePattern,
		arg.Capacity,
		arg.RefillTokens,
		arg.RefillIntervalSeconds,
	)
	var i RateLimitPolicy
	err := row.Scan(
		&i.ID,
		&i.ScopeType,
		&i.ScopeIdentifier,
		&i.RoutePattern,
		&i.Capacity,
		&i.RefillTokens,
		&i.RefillIntervalSeconds,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deactivateRateLimitPolicy = `-- name: DeactivateRateLimitPolicy :one
UPDATE rate_limit_policies
SET is_active = FALSE
WHERE id = $1
RETURNING id, scope_type, scope_identifier, route_pattern, capacity, refill_tokens, refill_interval_seconds, is_active, created_at, updated_at
`

func (q *Queries) DeactivateRateLimitPolicy(ctx context.Context, id uuid.UUID) (RateLimitPolicy, error) {
	row := q.db.QueryRow(ctx, deactivateRateLimitPolicy, id)
	var i RateLimitPolicy
	err := row.Scan(
		&i.ID,
		&i.ScopeType,
		&i.ScopeIdentifier,
		&i.RoutePattern,
		&i.Capacity,
		&i.RefillTokens,
		&i.RefillIntervalSeconds,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findRateLimitPolicyByScope = `-- name: FindRateLimitPolicyByScope :one
SELECT id, scope_type, scope_identifier, route_pattern, capacity, refill_tokens, refill_interval_seconds, is_active, created_at, updated_at
FROM rate_limit_policies
WHERE is_active = TRUE
  AND scope_type = $1
  AND scope_identifier IS NOT DISTINCT FROM $2
  AND route_pattern IS NOT DISTINCT FROM $3
LIMIT 1
`

type FindRateLimitPolicyByScopeParams struct {
	ScopeType       string      `db:"scope_type" json:"scope_type"`
	ScopeIdentifier pgtype.UUID `db:"scope_identifier" json:"scope_identifier"`
	RoutePattern    *string     `db:"route_pattern" json:"route_pattern"`
}

func (q *Queries) FindRateLimitPolicyByScope(ctx context.Context, arg FindRateLimitPolicyByScopeParams) (RateLimitPolicy, error) {
	row := q.db.QueryRow(ctx, findRateLimitPolicyByScope, arg.ScopeType, arg.ScopeIdentifier, arg.RoutePattern)
	var i RateLimitPolicy
	err := row.Scan(
		&i.ID,
		&i.ScopeType,
		&i.ScopeIdentifier,
		&i.RoutePattern,
		&i.Capacity,
		&i.RefillTokens,
		&i.RefillIntervalSeconds,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRateLimitPolicy = `-- name: GetRateLimitPolicy :one
SELECT id, scope_type, scope_identifier, route_pattern, capacity, refill_tokens, refill_interval_seconds, is_active, created_at, updated_at
FROM rate_limit_policies
WHERE id = $1
`

func (q *Queries) GetRateLimitPolicy(ctx context.Context, id uuid.UUID) (RateLimitPolicy, error) {
	row := q.db.QueryRow(ctx, getRateLimitPolicy, id)
	var i RateLimitPolicy
	err := row.Scan(
		&i.ID,
		&i.ScopeType,
		&i.ScopeIdentifier,
		&i.RoutePattern,
		&i.Capacity,
		&i.RefillTokens,
		&i.RefillIntervalSeconds,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveRateLimitPolicies = `-- name: ListActiveRateLimitPolicies :many
SELECT id, scope_type, scope_identifier, route_pattern, capacity, refill_tokens, refill_interval_seconds, is_active, created_at, updated_at
FROM rate_limit_policies
WHERE is_active = TRUE
ORDER BY scope_type, created_at DESC
`

func (q *Queries) ListActiveRateLimitPolicies(ctx context.Context) ([]RateLimitPolicy, error) {
	rows, err := q.db.Query(ctx, listActiveRateLimitPolicies)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RateLimitPolicy{}
	for rows.Next() {
		var i RateLimitPolicy
		if err := rows.Scan(
			&i.ID,
			&i.ScopeType,
			&i.ScopeIdentifier,
			&i.RoutePattern,
			&i.Capacity,
			&i.RefillTokens,
			&i.RefillIntervalSeconds,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRateLimitPolicies = `-- name: ListRateLimitPolicies :many
SELECT id, scope_type, scope_identifier, route_pattern, capacity, refill_tokens, refill_interval_seconds, is_active, created_at, updated_at
FROM rate_limit_policies
ORDER BY created_at DESC
`

func (q *Queries) ListRateLimitPolicies(ctx context.Context) ([]RateLimitPolicy, error) {
	rows, err := q.db.Query(ctx, listRateLimitPolicies)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RateLimitPolicy{}
	for rows.Next() {
		var i RateLimitPolicy
		if err := rows.Scan(
			&i.ID,
			&i.ScopeType,
			&i.ScopeIdentifier,
			&i.RoutePattern,
			&i.Capacity,
			&i.RefillTokens,
			&i.RefillIntervalSeconds,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRateLimitPolicy = `-- name: UpdateRateLimitPolicy :one
UPDATE rate_limit_policies
SET scope_type = $2,
    scope_identifier = $3,
    route_pattern = $4,
    capacity = $5,
    refill_tokens = $6,
    refill_interval_seconds = $7,
    is_active = $8
WHERE id = $1
RETURNING id, scope_type, scope_identifier, route_pattern, capacity, refill_tokens, refill_interval_seconds, is_active, created_at, updated_at
`

type UpdateRateLimitPolicyParams struct {
	ID                    uuid.UUID   `db:"id" json:"id"`
	ScopeType             string      `db:"scope_type" json:"scope_type"`
	ScopeIdentifier       pgtype.UUID `db:"scope_identifier" json:"scope_identifier"`
	RoutePattern          *string     `db:"route_pattern" json:"route_pattern"`
	Capacity              int32       `db:"capacity" json:"capacity"`
	RefillTokens          int32       `db:"refill_tokens" json:"refill_tokens"`
	RefillIntervalSeconds int32       `db:"refill_interval_seconds" json:"refill_interval_seconds"`
	IsActive              bool        `db:"is_active" json:"is_active"`
}

func (q *Queries) UpdateRateLimitPolicy(ctx context.Context, arg UpdateRateLimitPolicyParams) (RateLimitPolicy, error) {
	row := q.db.QueryRow(ctx, updateRateLimitPolicy,
		arg.ID,
		arg.ScopeType,
		arg.ScopeIdentifier,
		arg.RoutePattern,
		arg.Capacity,
		arg.RefillTokens,
		arg.RefillIntervalSeconds,
		arg.IsActive,
	)
	var i RateLimitPolicy
	err := row.Scan(
		&i.ID,
		&i.ScopeType,
		&i.ScopeIdentifier,
		&i.RoutePattern,
		&i.Capacity,
		&i.RefillTokens,
		&i.RefillIntervalSeconds,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
