// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: request_audit_logs.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createRequestAuditLog = `-- name: CreateRequestAuditLog :one
INSERT INTO request_audit_logs (
    api_key_id,
    route_id,
    policy_id,
    outcome,
    request_cost,
    tokens_remaining
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
)
RETURNING id, api_key_id, route_id, policy_id, outcome, request_cost, tokens_remaining, blocked_at
`

type CreateRequestAuditLogParams struct {
	ApiKeyID        pgtype.UUID `db:"api_key_id" json:"api_key_id"`
	RouteID         string      `db:"route_id" json:"route_id"`
	PolicyID        pgtype.UUID `db:"policy_id" json:"policy_id"`
	Outcome         string      `db:"outcome" json:"outcome"`
	RequestCost     int32       `db:"request_cost" json:"request_cost"`
	TokensRemaining int32       `db:"tokens_remaining" json:"tokens_remaining"`
}

func (q *Queries) CreateRequestAuditLog(ctx context.Context, arg CreateRequestAuditLogParams) (RequestAuditLog, error) {
	row := q.db.QueryRow(ctx, createRequestAuditLog,
		arg.ApiKeyID,
		arg.RouteID,
		arg.PolicyID,
		arg.Outcome,
		arg.RequestCost,
		arg.TokensRemaining,
	)
	var i RequestAuditLog
	err := row.Scan(
		&i.ID,
		&i.ApiKeyID,
		&i.RouteID,
		&i.PolicyID,
		&i.Outcome,
		&i.RequestCost,
		&i.TokensRemaining,
		&i.BlockedAt,
	)
	return i, err
}

const listRecentRequestAuditLogs = `-- name: ListRecentRequestAuditLogs :many
SELECT id, api_key_id, route_id, policy_id, outcome, request_cost, tokens_remaining, blocked_at
FROM request_audit_logs
ORDER BY blocked_at DESC
LIMIT $1
`

func (q *Queries) ListRecentRequestAuditLogs(ctx context.Context, limit int32) ([]RequestAuditLog, error) {
	rows, err := q.db.Query(ctx, listRecentRequestAuditLogs, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RequestAuditLog{}
	for rows.Next() {
		var i RequestAuditLog
		if err := rows.Scan(
			&i.ID,
			&i.ApiKeyID,
			&i.RouteID,
			&i.PolicyID,
			&i.Outcome,
			&i.RequestCost,
			&i.TokensRemaining,
			&i.BlockedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
